python scripts/plot_allgather_compute_impact.py
python scripts/plot_nvlink_p2p_compute_impact_vs_size.py
python scripts/plot_nvlink_p2p_bandwidth_vs_size.py
python scripts/plot_rdma_p2p_bandwidth_vs_qp.py
python scripts/plot_rdma_p2p_bandwidth_vs_size.py
python scripts/plot_rdma_p2p_compute_impact_vs_qp.py
